/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model2(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/untitl6ed.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_house_type03.geometry}
        material={materials.border}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_house_type03_1.geometry}
        material={materials.window}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_house_type03_2.geometry}
        material={materials.door}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_house_type03_3.geometry}
        material={materials._defaultMat}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_house_type03_4.geometry}
        material={materials.roof}
      />
    </group>
  );
}

useGLTF.preload("/untitl6ed.glb");
